declare module 'rollup-plugin-json';
declare module 'rollup-plugin-babel';
declare module 'rollup-plugin-uglify';
declare module 'rollup-plugin-node-builtins';
declare module 'rollup-plugin-node-globals';
declare module 'jest-in-case';
declare module 'jest-serializer-path';
declare module 'rimraf';
declare module 'ramda-extension';
